name = "Maracas"
uuid = "329a7628-3119-536a-a060-c6b2f8e35265"
authors = ["Grégory Salvan <apieum@gmail.com>"]
keywords = ["testing", "BDD"]
license = "MIT"
desc = "Prettify julia default Test package"
version = "1.1.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "≥ 0.7.0"
